
def malaysia_city_list():
    cities = [
    "City", "Pulau Pinang", "Balik Pulau", "Batu Ferringhi", "Tanjung Bungah", "Penang Hill",
    "Ayer Itam", "Jelutong", "Gelugor", "USM Pulau Pinang", "Bayan Lepas", "Batu Maung",
    "Butterworth", "Penaga", "Kepala Batas", "Tasek Gelugor", "Permatang Pauh", "Perai",
    "Bukit Mertajam", "Simpang Ampat", "Sungai Jawi", "Bandar Baharu", "Nibong Tebal", "Kubang Semang",
    "Kota Bharu", "Bachok", "Wakaf Bharu", "Tumpat", "Melor", "Ketereh",
    "Kem Desa Pahlawan", "Pulai Chondong", "Cherang Ruku", "Pasir Puteh", "Selising", "Pasir Mas",
    "Rantau Panjang", "Tanah Merah", "Jeli", "Kuala Balah", "Ayer Lanas", "Kuala Krai",
    "Dabong", "Gua Musang", "Temangan", "Machang", "Kuala Terengganu", "Bukit Payong",
    "Chalok", "Sungai Tong", "Marang", "Kuala Berang", "Ajil", "Jerteh",
    "Permaisuri", "Kampung Raja", "Kuala Besut", "Dungun", "Paka", "Bukit Besi",
    "Ketengah Jaya", "Al Muktatfi Billah Shah", "Cukai", "Ayer Puteh", "Ceneh", "Kijal",
    "Kemasek", "Kerteh", "Kuantan", "Bukit Goh", "Balok", "Bukit Kuin",
    "Sungai Lembing", "Gambang", "Bandar Pusat Jengka", "Maran", "Pekan", "Chini",
    "Muadzam Shah", "Kuala Rompin", "Bandar Tun Abdul Razak", "Jerantut", "Damak", "Padang Tengku",
    "Kuala Lipis", "Benta", "Dong", "Raub", "Sungai Koyan", "Sega",
    "Temerloh", "Kuala Krau", "Chenor", "Bandar Bera", "Triang", "Kemayan",
    "Mentakab", "Lanchang", "Karak", "Bentong", "Lurah Bilut", "Ipoh",
    "Batu Gajah", "Sungai Siput", "Ulu Kinta", "Chemor", "Tanjong Rambutan", "Kampung Kepayang",
    "Pusing", "Gopeng", "Malim Nawar", "Tronoh", "Tanjong Tualang", "Jeram",
    "Kampar", "Sitiawan", "Seri Manjung", "TLDM Lumut", "Lumut", "Pangkor",
    "Ayer Tawar", "Changkat Keruing", "Bota", "Bandar Seri Iskandar", "Bruas", "Parit",
    "Lambor Kanan", "Kuala Kangsar", "Pengkalan Hulu", "Intan", "Gerik", "Lenggong",
    "Sauk", "Enggor", "Padang Rengas", "Manong", "Taiping", "Selama",
    "Parit Buntar", "Tanjong Piandang", "Bagan Serai", "Kuala Kurau", "Simpang Ampat Semanggol", "Batu Kurau",
    "Kamunting", "Kuala Sepetang", "Simpang", "Matang", "Trong", "Changkat Jering",
    "Pantai Remis", "Tapah", "Chenderiang", "Temoh", "Tapah Road", "Bidor",
    "Sungkai", "Trolak", "Slim River", "Tanjong Malim", "Behrang Stesen", "Teluk Intan",
    "Bagan Datoh", "Selekoh", "Sungai Sumun", "Hutan Melintang", "Ulu Bernam", "Chenderong Balai",
    "Langkap", "Chikus", "Kampung Gajah", "Tanah Rata", "Brinchang", "Ringlet",
    "Shah Alam", "Klang", "Pelabuhan Klang", "Kapar", "Bandar Puncak Alam", "Telok Panglima Garang",
    "Jenjarom", "Banting", "Tanjong Sepat", "Pulau Indah", "Pulau Ketam", "Pulau Carey",
    "Kajang", "Hulu Langat", "Cheras", "Seri Kembangan", "Serdang", "Semenyih",
    "Bandar Baru Bangi", "Beranang", "Dengkil", "Sepang", "Sungai Pelek", "Kuala Kubu Baru",
    "Kerling", "Rasa", "Batang Kali", "Kuala Selangor", "Sungai Ayer Tawar", "Sabak Bernam",
    "Sungai Besar", "Sekinchan", "Tanjong Karang", "Bestari Jaya", "Bukit Rotan", "Petaling Jaya",
    "Sungai Buloh", "Puchong", "Subang Jaya", "Rawang", "Kuang", "Batu Arang",
    "Serendah", "Bukit Fraser", "Kuala Lumpur", "Putrajaya", "Cyberjaya", "KLIA",
    "Ampang", "Batu Caves", "Genting Highlands", "Seremban", "Port Dickson", "Si Rusa",
    "Rantau", "Linggi", "Rembau", "Kota", "Tanjong Ipoh", "Kuala Klawang",
    "Mantin", "Bandar Enstek", "Nilai", "Niai", "Labu", "Kuala Pilah",
    "Bahau", "Bandar Seri Jempol", "Batu Kikir", "Simpang Pertang", "Simpang Durian", "Tampin",
    "Johol", "Gemencheh", "Gemas", "Pusat Bandar Palong", "Rompin", "Melaka",
    "Ayer Keroh", "Durian Tunggal", "Kem Trendak", "Sungai Udang", "Tanjong Kling", "Jasin",
    "Asahan", "Bemban", "Merlimau", "Sungai Rambai", "Selandar", "Alor Gajah",
    "Lubok China", "Kuala Sungai Baru", "Masjid Tanah", "Iskandar Puteri", "Johor Bahru", "Kulai",
    "Senai", "Bandar Tenggara", "Gugusan Taib Andak", "Pekan Nenas", "Gelang Patah", "Pulau Satu",
    "Pengerang", "Pasir Gudang", "Masai", "Ulu Tiram", "Layang-Layang", "Kota Tinggi",
    "Ayer Tawar 2", "Bandar Penawar", "Pontian", "Ayer Baloi", "Benut", "Kukup",
    "Batu Pahat", "Rengit", "Senggarang", "Seri Gading", "Seri Medan", "Parit Sulong",
    "Semerah", "Yong Peng", "Muar", "Parit Jawa", "Bukit Pasir", "Sungai Mati",
    "Panchor", "Pagoh", "Gerisek", "Bukit Gambir", "Tangkak", "Segamat",
    "Batu Anam", "Jementah", "Labis", "Chaah", "Kluang", "Ayer Hitam",
    "Simpang Rengam", "Rengam", "Parit Raja", "Bekok", "Paloh", "Kahang",
    "Mersing", "Endau", "Labuan", "Kota Kinabalu", "Beverly", "Putatan",
    "Likas", "Inanam", "Tanjung Aru", "Keningau", "Kudat", "Kota Marudu",
    "Kota Belud", "Tuaran", "Tamparuli", "Tenghilan", "Ranau", "Penampang",
    "Papar", "Tambunan", "Bongawan", "Membakut", "Kuala Penyu",
    "Menumbok", "Beaufort", "Sipitang", "Tenom", "Nabawan", "Sandakan",
    "Beluran", "Kota Kinabatangan", "Pamol", "Tawau", "Lahad Datu", "Kunak",
    "Semporna", "Kuching", "Bau", "Siburan", "Kota Samarahan", "Lundu",
    "Asajaya", "Kabong", "Serian", "Simunjan", "Sebuyau", "Lingga",
    "Pusa", "Sri Aman", "Roban", "Saratok", "Debak", "Spaoh",
    "Betong", "Engkilili", "Lubok Antu", "Sibu", "Sarikei", "Belawai",
    "Daro", "Matu", "Dalat", "Balingian", "Mukah", "Bintangor",
    "Julau", "Kanowit", "Kapit", "Song", "Belaga", "Bintulu",
    "Sebauh", "Tatau", "Miri", "Baram", "Lutong", "Bekenu",
    "Niah", "Long Lama", "Limbang", "Nanga Medamit", "Sundar", "Lawas",
    "Kangar", "Kuala Perlis", "Padang Besar", "Kaki Bukit", "Arau", "Alor Setar",
    "Jitra", "Changloon", "Universiti Utara Malaysia", "Bukit Kayu Hitam", "Kodiang", "Kuala Nerang",
    "Pokok Sena", "Langgar", "Kuala Kedah", "Simpang Empat", "Pendang", "Kota Sarang Semut",
    "Yan", "Langkawi", "Sungai Petani", "Bedong", "Sik", "Gurun",
    "Jeniang", "Merbok", "Kota Kuala Muda", "Kulim", "Baling", "Kuala Pegang",
    "Kupang", "Kuala Ketil", "Padang Serai", "Lunas", "Karangan"
]

    return cities